### ISSUE TITLE
Python compliains it cant find the statistics library

### ISSUE THREAD

**Issue by soothill** [ReneSmeekes/storj_earnings#12]
Running this with the command python earnings.py /storjnode/storage gives the error :-

Traceback (most recent call last):
  File "earnings.py", line 6, in <module>
    from statistics import mean
ImportError: No module named statistics

Running a find on statistics.py finds it here :- 
/usr/lib/python3.7/statistics.py

Running python3 earnings.py /storjnode/storage works correctly.

This problem is on 2 different versions of linux one being a standard Raspberry Pi install so I suspect alot of other people may come across this problem.

**Comment by ReneSmeekes** [comment]
Fixed in v9.1.1! Thanks for letting me know
