### ISSUE TITLE
sqlite3 error :  audit_unknown_reputation_score

### ISSUE THREAD

**Issue by S0litaire** [ReneSmeekes/storj_earnings#14]
Just pulled the latest version and getting the following error when I run it:

```
python3 /home/User/source/storj_earnings/earnings.py /home/User/node2/ >> /home/User/Earnings/test2.txt
Traceback (most recent call last):
  File "/home/User/source/storj_earnings/earnings.py", line 283, in <module>
    for data in con.execute(query):
sqlite3.OperationalError: no such column: audit_unknown_reputation_score
```
Running Ubuntu 20.04 server
Storj version : v1.5.2

It ran correctly on the previous build (it runs it automatically every 30th of the month)

**Comment by ReneSmeekes** [comment]
Please update your node to v1.6.4. This new score was added in v1.6.3. This update should now be available for everyone.
