### ISSUE TITLE
sqlite error

### ISSUE THREAD

**Issue by ReneSch** [ReneSmeekes/storj_earnings#16]
Hey there,
while i´m running the script on 2 different nodes i got the same error:
# python3 earnings.py /opt/containers/storj/data/
Traceback (most recent call last):
  File "earnings.py", line 286, in <module>
    for data in con.execute(query):
sqlite3.OperationalError: no such column: disqualified_at

do you have a idea?
Best wishes

**Comment by ReneSmeekes** [comment]
Yep, please update your node to v1.12 or later. Today's update of the earnings script is not compatible with older node versions. Storagenode v1.12 should now be available for all OS's and docker setups.

**Comment by ReneSch** [comment]
Yup, that did the trick.
thanks very much!

**Comment by bota87** [comment]
what if I already have v1.12.3 but have this error
`Traceback (most recent call last):
  File "earnings.py", line 282, in <module>
    for data in con.execute(query):
sqlite3.OperationalError: no such column: disqualified`

**Comment by ReneSmeekes** [comment]
Then you need to update this script to the latest version too.

**Comment by bota87** [comment]
Sorry for the waste of time, I was sure I'm using the latest version.
Can close the issue for me

**Comment by ReneSmeekes** [comment]
I left this open in case someone was still running older versions of either. I think most will have updated by now, so I'll close this issue.
