### ISSUE TITLE
not work on 0.22.1 node

### ISSUE THREAD

**Issue by aleksandrko** [ReneSmeekes/storj_earnings#2]
not work

python3 current_earnings.py /storj/data/store/storage/
Traceback (most recent call last):
  File "current_earnings.py", line 155, in <module>
    for data in con.execute(query):
sqlite3.OperationalError: no such table: storage_usage

**Comment by ReneSmeekes** [comment]
fixed in https://github.com/ReneSmeekes/storj_earnings/commit/2bb1af41b53f0f457ca7acf555496020a2033a61
