### ISSUE TITLE
Update estimated earnings and analysis to new payout structure

### ISSUE THREAD

**Issue by GollyTicker** [ReneSmeekes/storj_earnings#21]
Hey, I've been using this tool since months and really like it, as it gives detailed analysis as well as the vetting status.

There has been lots of discussion regarding the SNO payouts in the past few months. A new payout structure for the three sattellites eu-north-1, us2 and saltlake was published: https://forum.storj.io/t/update-proposal-for-storage-node-operators-open-for-comments/22339

Do you plan to update the scripts to incorporate the new payment structure?

Kinds

**Comment by ReneSmeekes** [comment]
I just released version 13.0.0 which incorporates changes to facilitate different payout schemes per satellite. Have a look and let me know what you think!

**Comment by GollyTicker** [comment]
Great! Thanks for the update!

It looks fine on my computer.

However, I think the payout rates for the sattelites are a bit too close to the other text and it's a bit claustrophobic.
I'd prefer to have anouther empty line between both. But do as you wish :)

![image](https://user-images.githubusercontent.com/4527862/233356386-7f628998-b5ea-47e7-a2b1-827527514bfb.png)
