### ISSUE TITLE
Divide by Zero

### ISSUE THREAD

**Issue by DrGuns4Hands** [ReneSmeekes/storj_earnings#22]
Divide by Zero error
![image](https://github.com/ReneSmeekes/storj_earnings/assets/4683810/969cfa10-7bf1-418a-bd91-5609e2afedbd)

**Comment by ReneSmeekes** [comment]
Is this a new node? It seems the array that holds payout info is empty. That can happen if satellites have never reported it back so far. If it is a new node, give it a few hours and try again.

**Comment by DrGuns4Hands** [comment]
The node has been in place for a couple years. It was suspended due to some
issues and has come off suspension recently.

**Comment by DrGuns4Hands** [comment]
This was an issue on my own end. My resolution for the suspension involved me copying everything to a new drive. When I updated to the latest version of earnings.py I put it on the drive that I'm no longer using.
