### ISSUE TITLE
New Payout Structure

### ISSUE THREAD

**Issue by DrGuns4Hands** [ReneSmeekes/storj_earnings#23]
Storj has changed their pricing model for several satellites as indicated in this  forum post. 
https://forum.storj.io/t/announcement-changes-to-storj-node-payouts/22338

The text on the Earnings calculator still shows the old values for these satellites. Is the calculation for these satellites correct and just the text wrong or are both wrong? 

![image](https://github.com/ReneSmeekes/storj_earnings/assets/4683810/f89ba216-635b-40d9-a2c8-c4793f09002b)

**Comment by ReneSmeekes** [comment]
The satellites haven't yet reported back the changed pricing model. This is on Storj's end.
