### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by GollyTicker** [ReneSmeekes/storj_earnings#24]
```
Traceback (most recent call last):
  File "/home/<my-home>/storj/analysis/earnings-ReneSmeekes/earnings.py", line 475, in <module>
    avg_get_payout = sum(get_payout)/len(get_payout)
ZeroDivisionError: division by zero
```

Starting this month, it seems that the computations are failing.

My payout in the Storj UI looks normal however. Do you or others also have this problem?

I'm running the latest v13.0.3 release code.

**Comment by GollyTicker** [comment]
The error randomly went away and I cannot erproduce it. Guess it's not relevant then.

**Comment by ReneSmeekes** [comment]
Going by the line that threw the error this could have only happened if for some reason your pricing.db file had no pricing info for any of the satellites. Glad it resolved itself though.

**Comment by GollyTicker** [comment]
Given that it happened right after the new month started - could it perhaps be, because there was not feedback from the satellites yet for the new month? Or should this not matter?
