### ISSUE TITLE
deprecated datetime issue with python 3.12.2

### ISSUE THREAD

**Issue by kocoten1992** [ReneSmeekes/storj_earnings#25]
Hi, I got this error when try to run with python 3.12.2:

```
./earnings.py:87: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  mdate = datetime.utcnow()

./earnings.py:377: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  month_passed = (datetime.utcnow() - date_from).total_seconds() / (hours_this_month*3600)
```

**Comment by APCBoston** [comment]
@kocoten1992 those are warnings, not errors.  If this is the only "error", you should be able to run it fine on Python 3.12.2.  IIRC these `datetime` functions are scheduled for removal in 3.14, so the code will need to be updated for compatibility with that version.

**Comment by ReneSmeekes** [comment]
Thanks for the report. This has now been fixed in the latest release.
https://github.com/ReneSmeekes/storj_earnings/releases/tag/v13.2.0
