### ISSUE TITLE
Getting errors when running the script

### ISSUE THREAD

**Issue by soothill** [ReneSmeekes/storj_earnings#3]
I am getting these errors:-
<sqlite3.Cursor object at 0x7ff367c3d8f0>
<sqlite3.Cursor object at 0x7ff367c3d8f0>

At the start of the script the rest of it seems to be running but the payout numbers appear to be very low.

**Comment by subwolf** [comment]
Those messages seem more informational than errors, in brackets like that indicates a memory position.

**Comment by ReneSmeekes** [comment]
That was a result of leaving some debug print lines in. My bad. Should be resolved several versions ago already. :)
Thanks for the feedback!
