### ISSUE TITLE
Locking

### ISSUE THREAD

**Issue by smurfix** [ReneSmeekes/storj_earnings#5]
Umm, you might want to talk to the author of sqlite3. Corruption can only occur when file locking is not working, which only happens when the database in question resides on shared storage. (Accessing files on the same machine via different Docker containers doesn't count as shared storage, because there is only one OS kernel and no network protocol involved.)

Locally there's no way the database can get corrupted using this script, esp. not when one of the processes in question doesn't even write to it. No need for shutting down the node, let alone copy the files.

**Comment by ReneSmeekes** [comment]
Unfortunately docker on Windows and MacOS uses virtualization and networking protocols to deal with mounts. In theory you're right and it should not be an issue on Linux or with the GUI install in windows. And to be honest, I'm using this on Linux without making copies as well. I haven't tested this on the windows GUI install though, but I'm pretty sure it will work without issue there too. You just get extra careful after it has destroyed some peoples nodes. Still feel kind of bad about that.

**Comment by ReneSmeekes** [comment]
I've changed the warning to only apply to docker installs on windows or mac.
